### ISSUE TITLE
RCRM Job Description Formatting not carrying over

### ISSUE THREAD

**Issue by nkumar-topcoder** [topcoder-platform/taas-es-processor#19]
Please check below issue link, since, it's related to posting to zapier i have a raise issue here.

https://github.com/topcoder-platform/taas-app/issues/74

CC: @maxceem @imcaizheng I have requested for more clarity, Please wait for my confirmation before assigning

**Comment by maxceem** [comment]
@nkumar-topcoder as per our call this looks not like API issue and we have to solve it some other way, so I'm closing it here, but still keeping https://github.com/topcoder-platform/taas-app/issues/74 to track the progress for this issue.
